version: '3.8'

services:
  ms-catalog:
    build:
      context: ./ms-catalog
    container_name: ms-catalog
    ports:
      - "4001:4001"
    networks:
      - app-net

  ms-inventory:
    build:
      context: ./ms-inventory
    container_name: ms-inventory
    ports:
      - "4002:4002"
    networks:
      - app-net
    depends_on:
      - ms-catalog

  ms-payment:
    build:
      context: ./ms-payment
    container_name: ms-payment
    ports:
      - "4003:4003"
    networks:
      - app-net
    depends_on:
      - ms-inventory
      - ms-catalog

  ms-purchase:
    build:
      context: ./ms-purchase
    container_name: ms-purchase
    ports:
      - "4004:4004"
    networks:
      - app-net
    depends_on:
      - ms-catalog

  orchestrator:
    build:
      context: ./orchestrator
    container_name: orchestrator
    ports:
      - "4000:4000"
    networks:
      - app-net
    depends_on:
      - ms-catalog
      - ms-inventory
      - ms-payment
      - ms-purchase

networks:
  app-net:
    driver: bridge
