version: '3.8'

services:
  ms-catalog:
    build:
      context: ./ms-catalog
    container_name: ms-catalog
    ports:
      - "4001:4001"
    networks:
      - app-net
    environment:
      - DATABASE_URL=postgres://postgres:banana@postgres:5432/microservicios
    depends_on:
      - postgres

  ms-inventory:
    build:
      context: ./ms-inventory
    container_name: ms-inventory
    ports:
      - "4002:4002"
    networks:
      - app-net
    environment:
      - DATABASE_URL=postgres://postgres:banana@postgres:5432/microservicios
    depends_on:
      - postgres
      - ms-catalog

  ms-payment:
    build:
      context: ./ms-payment
    container_name: ms-payment
    ports:
      - "4003:4003"
    networks:
      - app-net
    environment:
      - DATABASE_URL=postgres://postgres:banana@postgres:5432/microservicios
    depends_on:
      - postgres
      - ms-inventory
      - ms-catalog

  ms-purchase:
    build:
      context: ./ms-purchase
    container_name: ms-purchase
    ports:
      - "4004:4004"
    networks:
      - app-net
    environment:
      - DATABASE_URL=postgres://postgres:banana@postgres:5432/microservicios
    depends_on:
      - postgres
      - ms-catalog

  orchestrator:
    build:
      context: ./orchestrator
    container_name: orchestrator
    ports:
      - "4000:4000"
    networks:
      - app-net
    depends_on:
      - ms-catalog
      - ms-inventory
      - ms-payment
      - ms-purchase

  postgres:
    image: postgres:latest  
    container_name: postgres
    environment:
      POSTGRES_USER: postgres  # Nombre de usuario de la base de datos
      POSTGRES_PASSWORD: banana  # Contraseña para el usuario
      POSTGRES_DB: microservicios  # Nombre de la base de datos
    ports:
      - "5432:5432"  # Exponer el puerto de PostgreSQL
    networks:
      - app-net  # Conectar PostgreSQL a la misma red interna
    volumes:
      - postgres-data:/var/lib/postgres/data  # Volumen para persistencia de datos

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./orchestrator/src/tests/k6:/tests 
    networks:
      - app-net
    depends_on:
      - orchestrator  


networks:
  app-net:
    driver: bridge

volumes:
  postgres-data:  # Definir volumen persistente para los datos de PostgreSQL